stages:
- build
- pack
- publish

before_script:
- chcp 65001

build:
  tags: 
  - windows
  - vs2015  
  stage: build  
  script:
  - echo Restoring packages
  - dotnet restore .\src\RabbitLink
  - echo Building
  - dotnet build .\src\RabbitLink -c release

pack:
  tags: 
  - windows
  stage: pack
  only:
  - /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/
  except:
  - branches
#  - triggers  
  dependencies:
    - build
  script:
  - echo Restoring packages
  - dotnet restore .\src\RabbitLink
  - echo Building
  - dotnet pack .\src\RabbitLink -o artifacts\ --configuration release 
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*.nupkg

publish:
#  when: manual
  tags:
  - windows
  stage: publish
  only:
  - /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/
  except:
  - branches
#  - triggers
  dependencies:
  - pack
  script:
  - echo "Publishing nuget package"  
  - util\nuget.exe push artifacts\*.nupkg "%NUGET_API_KEY%" -NonInteractive