stages:
- build
- pack
- publish

before_script:
- chcp 65001

build:
  tags: 
  - windows
  - dotnet
  stage: build  
  script:
  - echo Restoring packages
  - dotnet restore "%cd%\src\RabbitLink"
  - dotnet restore "%cd%\src\RabbitLink.Serialization.Json"
  - echo Building
  - dotnet build "%cd%\src\RabbitLink" -c Release
  - dotnet build "%cd%\src\RabbitLink.Serialization.Json" -c Release

pack:
  tags: 
  - windows
  - dotnet
  stage: pack
  only:
  - /^v([0-9]+)(\.([0-9]+)){1,2}.*$/
  except:
  - branches
#  - triggers  
  dependencies:
    - build
  script:
  - echo Restoring packages
  - dotnet restore "%cd%\src\RabbitLink"
  - dotnet restore "%cd%\src\RabbitLink.Serialization.Json"
  - echo Building
  - dotnet pack "%cd%\src\RabbitLink" -c Release -o "%cd%\artifacts\"
  - dotnet pack "%cd%\src\RabbitLink.Serialization.Json" -c Release -o "%cd%\artifacts\"
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*

publish:
#  when: manual
  tags:
  - windows
  - dotnet
  stage: publish
  only:
  - /^v([0-9]+)(\.([0-9]+)){1,2}.*$/
  except:
  - branches
#  - triggers
  dependencies:
  - pack
  script:
  - echo "Publishing nuget package"  
  - dotnet nuget push --force-english-output -s https://api.nuget.org/v3/index.json -k "%NUGET_API_KEY%" artifacts\*.nupkg 