stages:
- build
- publish

build:nuget:
  tags: 
  - windows
  - vs2015
  stage: build
  script: build.cmd  
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*.nupkg

publish:nuget:
    when: manual
    tags:
    - windows
    stage: publish
#    only:
#    - /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/
#    except:
#    - branches
#    - triggers
    dependencies:
    - build:nuget
    script: publish.cmd
