stages:
- build
- pack
- publish

build:
  tags:
  - windows
  - dotnet
  stage: build
  script:
  - chcp 65001
  - echo Restoring packages
  - dotnet restore "%cd%\src\RabbitLink"
  - dotnet restore "%cd%\src\RabbitLink.Serialization.Json"
  - echo Building
  - dotnet build "%cd%\src\RabbitLink" -c Release
  - dotnet build "%cd%\src\RabbitLink.Serialization.Json" -c Release

nuget-main:
  tags:
  - windows
  - dotnet
  stage: pack
  only:
  - /^v([0-9]+)(\.([0-9]+)){1,2}.*$/
  except:
  - branches
  script:
  - chcp 65001
  - echo Restoring packages
  - dotnet restore "%cd%\src\RabbitLink"
  - echo Building
  - dotnet pack "%cd%\src\RabbitLink" -c Release -o "%cd%\artifacts\"
  - dotnet nuget push --force-english-output -s https://api.nuget.org/v3/index.json -k "%NUGET_API_KEY%" artifacts\*.nupkg
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*

nuget-json:
  tags:
  - windows
  - dotnet
  stage: pack
  only:
  - /^json-v([0-9]+)(\.([0-9]+)){1,2}.*$/
  except:
  - branches
  script:
  - chcp 65001
  - echo Restoring packages
  - dotnet restore "%cd%\src\RabbitLink.Serialization.Json"
  - echo Building
  - dotnet pack "%cd%\src\RabbitLink.Serialization.Json" -c Release -o "%cd%\artifacts\"
  - dotnet nuget push --force-english-output -s https://api.nuget.org/v3/index.json -k "%NUGET_API_KEY%" artifacts\*.nupkg
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*

